on: [push]

jobs:
  opa_test_job:
    runs-on: ubuntu-latest
    name: OPA test
    steps:
    - uses: actions/checkout@master
    - name: OPA test
      id: opa-test
      uses: jaspervdj-luminal/opa-test-action@master
      with:
        path: 'lib:test'
